version: 0.1
downloads:
  - name: task
    # executable: true
    downloads:
      - os:
          linux: linux
          macos: darwin
          # No windows release
        cpu:
          x86_64: amd64
          arm_64: arm64
        url: https://github.com/go-task/task/releases/download/v${version}/task_${os}_${cpu}.tar.gz
        # strip_components: 1
tools:
  definitions:
    - name: go-task
      download: task
      known_good_version: 3.33.1
      shims: [task]
