version: 3

dotenv:
  - .env

tasks:
  default: task --list-all

  env:
    - env | sort

  init:
    - go mod init github.com/metafeather/tools/devenv
    - changie init
    - goreleaser init
    - cobra-cli init --viper --author "Liam Clancy (metafeather) github@metafeather.com" --license apache
    - cobra-cli add init
    - cobra-cli add run
    - cobra-cli add doctor

  build:
    - goreleaser build --clean --snapshot --single-target

  run:
    - go run main.go {{.CLI_ARGS}}

  stdlib:
    - task --taskfile=embed/stdlib/Taskfile.yaml {{.CLI_ARGS}}

  change:
    - changie --projects="devenv" new

  changelog:
    - mkdir -p .changes/unreleased
    - changie --project="devenv" batch auto 2>/dev/null || true
    - changie merge

  prerelease:
    # NOTE(metafeather): goreleaser needs pro license to use prefixed tags so
    # prefix/v1.2.3 --> v1.2.3-prefix.1+123 during build/prerelease
    vars:
      TOOL_CURRENT_TAG:
        sh: |
          TOOL_CURRENT_TAG=$(changie --project="devenv" latest) 
          TAG_RESULT=$(git tag -f -a "${TOOL_CURRENT_TAG##devenv/}-devenv" -m "Devenv release ${TOOL_CURRENT_TAG}")
          echo "${TOOL_CURRENT_TAG}"
      TOOL_CURRENT_VERSION: '{{trimPrefix "devenv/" .TOOL_CURRENT_TAG}}'
    env:
      GORELEASER_CURRENT_TAG:
        # sh: svu --pattern="devenv/*" --prefix="devenv/v" --strip-prefix --directory="devenv" current
        sh: svu --pattern="*-devenv*" --build="goreleaser" prerelease --pre-release="devenv"
      # GORELEASER_PREVIOUS_TAG:
    cmds:
      - 'echo "Creating prerelease: ${GORELEASER_CURRENT_TAG} (from {{.TOOL_CURRENT_TAG}})"'
      - git tag -f -a "${GORELEASER_CURRENT_TAG}" -m "Devenv release {{.TOOL_CURRENT_TAG}}"
      - goreleaser release --clean --skip=validate --release-notes=".changes/{{.TOOL_CURRENT_TAG}}.md"

  rc:
    - brew update
    - brew upgrade metafeather/tools/devenv@1.0.0-rc

  release:
    # Ammend to use prefixed tag for release
    vars:
      TOOL_CURRENT_TAG:
        sh: changie --project="devenv" latest
    env:
      GORELEASER_CURRENT_TAG:
        sh: svu --pattern="*-devenv*" current
    cmds:
      - 'echo "Creating release: {{.TOOL_CURRENT_TAG}} (from ${GORELEASER_CURRENT_TAG})"'
      # NOTE(metafeather): dereferences existing annotated tag before copying
      - git tag -f {{.TOOL_CURRENT_TAG}} ${GORELEASER_CURRENT_TAG}^{commit}
      - git push origin refs/tags/{{.TOOL_CURRENT_TAG}}
      # ref: https://cli.github.com/manual/gh_release_edit
      - gh release edit "${GORELEASER_CURRENT_TAG}" --tag="{{.TOOL_CURRENT_TAG}}" --title="{{.TOOL_CURRENT_TAG}}" --latest
      - echo "Now edit the \`devenv\` version number in the Formula"
