version: 0.1
downloads:
  - name: seaweedfs
    # executable: true
    downloads:
      - os:
          linux: linux
          macos: darwin
        cpu:
          x86_64: amd64
          arm_64: arm64
        url: https://github.com/seaweedfs/seaweedfs/releases/download/${version}/${os}_${cpu}.tar.gz
      - os:
          windows: windows
        cpu:
          x86_64: amd64
        url: https://github.com/seaweedfs/seaweedfs/releases/download/${version}/${os}_${cpu}.tar.gz
tools:
  definitions:
    - name: seaweedfs
      download: seaweedfs
      known_good_version: 3.61
      shims: [weed]
