version: 0.1
tools:
  definitions:
    - name: dagster
      runtime: python
      package: dagster-dbt
      extra_packages:
        # - dagster
        # - dbt-core
        - dagster-webserver==1.6.2
        - dbt-duckdb==1.7.1
      shims:
        - dagster
        - dagster-dbt
      known_good_version: 0.22.0
